#!/usr/bin/env bash

# SET PWD TO DIRNAME OF THIS SCRIPT
# this script should always be located next to
# docker-compose.yml & the test_runner package
# directory (containing python env & tests)
current_dir=`dirname "$0"`
cd $current_dir
# Only use the following line if needing to enable
# a python environment
cd ..

prefix="releases/text-composer-"
# get line from package.json with version number
_current_version_raw=`rg version package.json`
# get substring from 14th character to end
_current_version_prefix_trimmed=${_current_version_raw:14}
# trim final ", from end of string to get version number
current_version=${_current_version_prefix_trimmed%"\","}

echo "Starting release script..."
echo ""
echo "Will release as version $current_version"

for file in "releases"/*; do
    file_version_and_suffix=${file#"$prefix"}
    if [[ $file_version_and_suffix == "$current_version.tgz" ]]; then
        echo "Found match: $file == $current_version"
        version_already_built=1
    fi
done

if [ $version_already_built ]; then
    echo ""
    echo "Version specified in ./app-version already exists. Update version"
    echo "& run again, or if you want to override an already built version,"
    echo "run this script again, passing the override argument:"
    echo ""
    echo "./scripts/build override"
    echo ""

    exit 1
fi

echo ""

# Build from current source
npm run build
# If error encountered while building, exit
if [[ $? == 1 ]]; then
    exit 1
fi

# By packing while in releases directory, the tarball will be saved here.
cd ./releases
npm pack ..
